#
# Workflow: Build PR
#

name: Build PR
on: pull_request

jobs:

  build-pr:

    name: "Build PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
    runs-on: ubuntu-latest

    steps:
    
      - name: Step 1
        shell: bash
        run: echo "step 1 of \#${{ github.event.pull_request.number }}"
        
      - name: Step 2
        shell: bash
        run: echo "step 2 of \#${{ github.event.pull_request.number }}"
