
name: Experiment
on: push

jobs:

  experiment:
    name: Experiment

    runs-on: ubuntu-latest

    steps:
      - name: Experiment
        uses: zpqrtbnk/gh-actions/experiment@master
        with:
          mode: woot
                  
      - name: Script
        uses: zpqrtbnk/gh-actions/jsaction@master
        with:
          githubToken: ${{ github.token }}
          text: zoot

      - name: Infos
        shell: bash
        run: |
          echo "github.ref: '${{ github.ref }}'"
          echo "github.sha: '${{ github.sha }}'"
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Embedded
        uses: ./.github/actions/test-action
        with:
          name: NAME
          path: PATH
          version: VERSION
