name: Toy with issue description
on:
    issues:
        types: labeled
        
jobs:
    toy-desc:
        runs-on: ubuntu-latest
        if: |
            !contains(github.event.issue.title, '!exclude!') ||
            contains(github.event.issue.title, '!force!')
        steps:
        - name: Toy with issue description
          uses: actions/github-script@v4.0.2
          with:
            script: |
                const title = `${{ github.event.issue.title }} !`
                const body = `updated\n${{ github.event.issue.body }}`
                github.issues.update({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    title: title,
                    body: body
                })
          