name: Test Push
on: push
jobs:
    foo:
        name: Foo
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            ref: ${{github.ref}}
            
        - name: Foo
          shell: bash
          run: |
            echo "foo" >> foo.txt

        - name: Push
          shell: bash
          run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "github-actions@hazelcast.com"
            git add foo.txt
            git commit -m "Foo"
            git push